import 'package:rune_of_the_day/app/constants/styles/icons.dart';

abstract class ImagePickerBase {
  String getImageById(int id);
}

class ImagePickerService extends ImagePickerBase {
  @override
  String getImageById(int id) {
    Map<int, String> idToImage = {
      23: aceofwands,
      24: twoofwands,
      25: threeofwands,
      26: fourofwands,
      27: fiveofwands,
      28: sixofwands,
      29: sevenofwands,
      30: eightofwands,
      31: nineofwands,
      32: tenofwands,
      33: pageofwands,
      34: knightofwands,
      35: queenofwands,
      36: kingofwands,
      37: aceofcups,
      38: twoofcups,
      39: threeofcups,
      40: fourofcups,
      41: fiveofcups,
      42: sixofcups,
      43: sevenofcups,
      44: eightofcups,
      45: nineofcups,
      46: tenofcups,
      47: pageofcups,
      48: knightofcups,
      49: queenofcups,
      50: kingofcups,
      51: aceofswords,
      52: twoofswords,
      53: threeofswords,
      54: fourofswords,
      55: fiveofswords,
      56: sixofswords,
      57: sevenofswords,
      58: eightofswords,
      59: nineofswords,
      60: tenofswords,
      61: pageofswords,
      62: knightofswords,
      63: queenofswords,
      64: kingofswords,
      65: aceofpentacles,
      66: twoofpentacles,
      67: threeofpentacles,
      68: fourofpentacles,
      69: fiveofpentacles,
      70: sixofpentacles,
      71: sevenofpentacles,
      72: eightofpentacles,
      73: nineofpentacles,
      74: tenofpentacles,
      75: pageofpentacles,
      76: knightofpentacles,
      77: queenofpentacles,
      78: kingofpentacles,
      1: thefool,
      2: themagician,
      3: thehighpriestess,
      4: theempress,
      5: theemperor,
      6: theheirophant,
      7: thelovers,
      8: strength,
      9: thehangedman,
      10: thechariot,
      11: justice,
      12: thehermit,
      13: wheeloffortune,
      14: death,
      15: temperance,
      16: thedevil,
      17: thetower,
      18: thestar,
      19: themoon,
      20: thesun,
      21: judgement,
      22: theworld,
    };

    return idToImage[id];
  }
}
